---
 hosts: private_repo
  order: sorted
  gather_facts: False
  tasks:
    - debug:
        var: inventory_hostname
- name: verdaccio installed
  npm:
    name: verdaccio
    version: "{{ verdaccio_version | default(omit) }}"
    global: true
  notify: restart verdaccio

- name: verdaccio user created
  user:
    name: verdaccio

- name: resolve npm config path
  command: npm config get prefix --no-update-notifier
  register: npm_config_prefix_resolve
  changed_when: false
  ignore_errors: true

- name: setup npm_config_prefix
  set_fact: npm_config_prefix = "{{ npm_config_prefix_resolve.stdout }}"
  when: >
    (npm_config_prefix_resolve.rc == 0) and
    ("FAILED" not in npm_config_prefix_resolve.stderr) and
    (npm_config_prefix_resolve.stdout != '')
- name: deploy verdaccio systemd unit
  template:
    src: verdaccio.service.j2
    dest: /etc/systemd/system/verdaccio.service
  notify: systemd daemon-reload

- name: verdaccio service enabled
  systemd:
    name: verdaccio
    enabled: true

- name: verdaccio directories creation
  file:
    path: "{{ item }}"
    state: directory
    owner: verdaccio
  loop:
    - "{{ verdaccio_datadir }}"
    - "{{ verdaccio_configdir }}"

- name: config deployed
  template:
    src: config.j2
    dest: "{{ verdaccio_configdir }}/verdaccio.yml"
    owner: verdaccio
  notify: restart verdaccio

- name: install logrotate script
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/verdaccio
    owner: root
    mode: 0644